openapi: 3.0.3
info:
  title: tuna
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /docs/openapi.json:
    get:
      tags:
      - crate
      summary: Retrieve json OpenAPI documentation
      description: |-
        Retrieve json OpenAPI documentation

        Requires: `DocsRead` permission
      operationId: docs_json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '403':
          description: Forbidden requires permission `DocsRead`
      security:
      - permissions:
        - DocsRead
  /docs/openapi.yaml:
    get:
      tags:
      - crate
      summary: Retrieve yaml OpenAPI documentation
      description: |-
        Retrieve yaml OpenAPI documentation

        Requires: `DocsRead` permission
      operationId: docs_yaml
      responses:
        '200':
          description: Success
          content:
            application/x-yaml:
              schema:
                type: string
        '403':
          description: Forbidden requires permission `DocsRead`
      security:
      - permissions:
        - DocsRead
components:
  schemas:
    DangerousLogin:
      type: object
      required:
      - username
      - password
      properties:
        password:
          type: string
          description: Your password
          example: jnoM76raK
        username:
          type: string
          description: Your username
          example: 5-pebbles
  securitySchemes:
    api_key:
      type: apiKey
      in: cookie
      name: permissions
