openapi: 3.0.3
info:
  title: tuna
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /docs/openapi.yaml:
    get:
      tags:
      - crate
      operationId: docs_yaml
      responses:
        '200':
          description: Success
          content:
            application/x-yaml:
              schema:
                type: string
        '403':
          description: Unauthorized, requires permission `DocsRead`
