name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Hurl
      uses: gacts/install-hurl@v1
      with:
        version: 4.1.0
    - name: Build Tests
      run: cargo test --no-run
    - name: Run Tests
      run: cargo test --no-fail-fast
